[project]
authors = [{name = "Kolen Cheung", email = "christian.kolen@gmail.com"}]
dependencies = []
name = "unified-keyboard-config"
requires-python = ">= 3.11"
version = "0.1.0"

[build-system]
build-backend = "hatchling.build"
requires = ["hatchling"]

[tool.pixi.workspace]
channels = ["conda-forge"]
platforms = ["win-64", "linux-64", "linux-aarch64", "osx-64", "osx-arm64"]

[tool.pixi.pypi-dependencies]
unified_keyboard_config = { path = ".", editable = true }

[tool.pixi.tasks]
submodule-init = { cmd = "git submodule update --init --recursive", description = "Initialize submodules after cloning" }
submodule-update = { cmd = "git submodule update --remote --recursive", description = "Update submodules from remote" }
update-moonlander = { cmd = "curl -L -o source.zip https://oryx.zsa.io/source/$ORYX_LAYOUT_HASH && unzip -o source.zip -d submodule/Moonlander-Mk1-QMK && rm source.zip && cd submodule/Moonlander-Mk1-QMK && git add . && git commit -m 'Update Moonlander firmware source'", description = "Update Moonlander firmware source from Oryx" }

[tool.pixi.activation.env]
ORYX_LAYOUT_HASH = "v65q0b"
